"""Data models for the trading system."""
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Literal, Optional


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class TradeStatus(str, Enum):
    PENDING = "pending"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    symbol: str
    side: Literal["buy", "sell"]
    strategy_name: str
    confidence: float  # 0.0 - 1.0
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class ValidationResult:
    """Result of risk validation."""
    approved: bool
    reason: Optional[str] = None
    adjusted_size: Optional[float] = None


@dataclass
class RiskConfig:
    """Risk management configuration."""
    max_position_pct: float = 0.10  # 10% of portfolio per position
    max_daily_loss_pct: float = 0.02  # 2% max daily loss
    max_positions: int = 5
    stop_loss_pct: float = 0.015  # 1.5% stop loss
    take_profit_pct: float = 0.02  # 2% take profit
    trailing_stop_activation: float = 0.02  # Activate trailing at 2% profit
    min_buying_power: float = 10.0  # Don't trade if buying power below this


@dataclass
class Trade:
    """Completed trade record."""
    id: Optional[int] = None
    timestamp: datetime = field(default_factory=datetime.now)
    symbol: str = ""
    side: str = ""
    qty: float = 0.0
    entry_price: float = 0.0
    exit_price: Optional[float] = None
    pnl: Optional[float] = None
    strategy: str = ""
    status: str = "pending"
    order_id: Optional[str] = None


@dataclass
class DailySummary:
    """End of day summary."""
    date: str
    starting_value: float
    ending_value: float
    pnl: float
    pnl_pct: float
    trades_executed: int
    winning_trades: int
    losing_trades: int
    strategies_used: list[str] = field(default_factory=list)


@dataclass
class Position:
    """Current position info."""
    symbol: str
    qty: float
    avg_entry_price: float
    current_price: float
    unrealized_pnl: float
    unrealized_pnl_pct: float


@dataclass 
class AccountInfo:
    """Account summary."""
    portfolio_value: float
    cash: float
    buying_power: float
    equity: float
    daily_pnl: float
    daily_pnl_pct: float
